#!/bin/bash
# radio 
# Copyright (C) 2010 David Serrano
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# With this script you can listen to a on-line radio station.
# usage:
# radio <station_name>

# Uncomment this line if you want to set a default
# radio station to be played when this script
# has no arguments.
#DEFRADIO=m80           # Default radio station

# Flags to pass to the player
if [ "$PLBFLAGS" = "" ]; then PLBFLAGS=-really-quiet; fi  # These are passed BEFORE the URL
if [ "$PLAFLAGS" = "" ]; then PLAFLAGS= > /dev/null; fi   # There are passed AFTER the URL

# The player to use
if [ "$PLAYER" = "" ]; then PLAYER=mplayer; fi

if [ "$1" != "" ]; then
    RADIO=$1
else
    RADIO=$DEFRADIO
fi

if [ "$RADIO" = "" ]; then
    echo No default radio station set
    echo usage: $0 "<radio_station>"

elif [ "$RADIO" = "amalia" ]; then URL=mms://stream.radio.com.pt/ROLI-ENC-496
elif [ "$RADIO" = "antena1" ]; then URL=http://195.245.168.21/antena1
elif [ "$RADIO" = "antena2" ]; then URL=http://195.245.168.21/antena2
elif [ "$RADIO" = "antena3" ]; then URL=http://195.245.168.21/antena3
elif [ "$RADIO" = "bestrock" ]; then URL=http://195.23.102.196/bestrockcbr20
elif [ "$RADIO" = "cidadefm" ]; then URL=http://195.23.102.196/cidadecbr20
elif [ "$RADIO" = "comercial" ]; then URL=http://195.23.102.196/comercialcbr20
elif [ "$RADIO" = "rfm" ]; then URL=http://stream2.rfm.pt/RFM
elif [ "$RADIO" = "m80" ]; then URL=http://195.23.102.196/m80cbr20
elif [ "$RADIO" = "marginal" ]; then URL=mms://stream.radio.com.pt/ROLI-ENC-499
elif [ "$RADIO" = "mixfm" ]; then URL=http://195.23.102.196/mixcbr96
elif [ "$RADIO" = "megafm" ]; then URL=http://stream2.mega.fm/MEGAFM
elif [ "$RADIO" = "orbital" ]; then URL=mms://stream.radio.com.pt/ROLI-ENC-401
elif [ "$RADIO" = "oxigenio" ]; then URL=mms://stream.radio.com.pt/ROLI-ENC-498
elif [ "$RADIO" = "radar" ]; then URL=mms://stream.radio.com.pt/ROLI-ENC-497
elif [ "$RADIO" = "rcp" ]; then URL=http://195.23.102.196/rcpcbr20
elif [ "$RADIO" = "romanticafm" ]; then URL=mms://212.113.177.246/foxxcbr20
elif [ "$RADIO" = "rr" ]; then URL=http://stream2.rr.pt/RR
elif [ "$RADIO" = "tsf" ]; then URL=icyx://tsfdirecto.tsf.pt/tsfdirecto.aac
# to add a new radio just add a line like the following:
# elif ["$RADIO" = "sample_radio_name" ]; then URL=mms://stream.example.com/sample_radio_name

# as you can see the line format is similiar to those presented above.
# figure it out on your own ;)

else
    echo "Non exitent radio station";
    exit 1;

fi

exec $PLAYER $PLBFLAGS $URL $PLAFLAGS
